version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: saad
      MONGO_INITDB_ROOT_PASSWORD: docker2025

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: saad
      ME_CONFIG_MONGODB_ADMINPASSWORD: docker2025
      ME_CONFIG_MONGODB_URL: mongodb://saad:docker2025@mongo:27017/